spring.profiles.default=production
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5433/prices
spring.datasource.username=postgres
spring.datasource.password=chambers
spring.jpa.hibernate.ddl-auto=false
spring.jpa.show-sql=true